org: mspolycarpo
app: my-serverless-challenge
service: my-serverless-challenge

frameworkVersion: '2'


plugins:
    - serverless-dynamodb-local
    - serverless-offline

custom:
  tableName: 'funcionarios-table-${self:provider.stage}'
  dynamodb:
    stages: 
      - dev
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ TabelaFuncionarios, Arn ]
  environment:
    TABELA_FUNCIONARIOS: ${self:custom.tableName}

functions:
  api:
    handler: src/handlers/handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    TabelaFuncionarios:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
